env: simple_matrix

env_args:
  n_agents: 2
  n_actions: 2
  episode_limit: 1
  seed: null

test_greedy: True
test_nepisode: 8
test_interval: 1000
log_interval: 1000
runner_log_interval: 1000
learner_log_interval: 1000
t_max: 2000
